// docs/apps/react-legacy/src/components/tree/TreeFilter.tsx
import { useRef } from 'react';
import { VirtTree, type VirtTreeRef } from '@virt-list/react-legacy';
import TreeEmpty from './items/TreeEmpty';
import '../../demo.css';

function generateTreeData() {
  return Array.from({ length: 40 }, (_, i) => ({
    id: String(i),
    title: `Node-${i}`,
    children: Array.from({ length: 3 }, (_, j) => ({
      id: `${i}-${j}`,
      title: `Node-${i}-${j}`,
      children: Array.from({ length: 2 }, (_, k) => ({
        id: `${i}-${j}-${k}`,
        title: `Node-${i}-${j}-${k}`,
      })),
    })),
  }));
}

export default function TreeFilter() {
  const treeRef = useRef<VirtTreeRef>(null);
  const filterInputRef = useRef<HTMLInputElement>(null);

  return (
    <div className="tree-demo">
      <div className="tree-btn-container">
        <div className="input-container">
          <input
            ref={filterInputRef}
            defaultValue="Node-0"
            style={{ width: 160, padding: '4px 8px', border: '1px solid #ddd', borderRadius: 4 }}
          />
          <button
            type="button"
            className="virt-list-btn virt-list-btn-primary"
            onClick={() => {
              const query = filterInputRef.current?.value ?? '';
              treeRef.current?.filter(query);
            }}
          >
            filter
          </button>
        </div>
      </div>
      <div className="virt-tree-wrapper" style={{ width: '100%', height: 400 }}>
        <VirtTree
          ref={treeRef}
          list={generateTreeData()}
          fieldNames={{ key: 'id' }}
          indent={20}
          filterMethod={(query, node) => (node.title ?? '').includes(query)}
          empty={() => <TreeEmpty />}
        />
      </div>
    </div>
  );
}

// docs/apps/vue/src/components/tree/TreeFilter.vue
<template>
  <div class="tree-demo">
    <div class="tree-btn-container">
      <div class="input-container">
        <input
          v-model="filterInput"
          style="width: 160px; padding: 4px 8px; border: 1px solid #ddd; border-radius: 4px"
        />
        <button type="button" class="virt-list-btn virt-list-btn-primary" @click="applyFilter">filter</button>
      </div>
    </div>
    <div class="virt-tree-wrapper">
      <VirtTree ref="treeRef" :list="treeData" :field-names="{ key: 'id' }" :indent="20" :filter-method="filterMethod">
        <template #empty>
          <TreeEmpty />
        </template>
      </VirtTree>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { VirtTree } from '@virt-list/vue';
import type { TreeNode } from '@virt-list/vue';
import type { VirtTreeRef } from '../_virtRefTypes';
import TreeEmpty from './items/TreeEmpty.vue';
import '../../demo.css';

function generateTreeData() {
  return Array.from({ length: 40 }, (_, i) => ({
    id: String(i),
    title: `Node-${i}`,
    children: Array.from({ length: 3 }, (_, j) => ({
      id: `${i}-${j}`,
      title: `Node-${i}-${j}`,
      children: Array.from({ length: 2 }, (_, k) => ({
        id: `${i}-${j}-${k}`,
        title: `Node-${i}-${j}-${k}`,
      })),
    })),
  }));
}

function filterMethod(query: string, node: TreeNode) {
  return node.title?.includes(query) ?? false;
}

const treeRef = ref<VirtTreeRef | null>(null);
const treeData = ref(generateTreeData());
const filterInput = ref('Node-0');

function applyFilter() {
  treeRef.value?.filter(filterInput.value);
}
</script>
