// docs/apps/vue/src/components/tree/TreeDefault.vue
<template>
  <div class="tree-demo">
    <div class="virt-tree-wrapper">
      <VirtTree :list="treeData" :field-names="{ key: 'id' }" :indent="20" selectable default-expand-all>
        <template #default="{ node }">
          <TreeDefaultItem :node="node" />
        </template>
        <template #empty>
          <TreeEmpty />
        </template>
      </VirtTree>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { VirtTree } from '@virt-list/vue';
import TreeDefaultItem from './items/TreeDefaultItem.vue';
import TreeEmpty from './items/TreeEmpty.vue';
import '../../demo.css';

function generateTreeData() {
  return Array.from({ length: 40 }, (_, i) => ({
    id: String(i),
    title: `Node-${i}`,
    children: Array.from({ length: 3 }, (_, j) => ({
      id: `${i}-${j}`,
      title: `Node-${i}-${j}`,
      children: Array.from({ length: 2 }, (_, k) => ({
        id: `${i}-${j}-${k}`,
        title: `Node-${i}-${j}-${k}`,
      })),
    })),
  }));
}

const treeData = ref(generateTreeData());
</script>

// docs/apps/react-legacy/src/components/tree/TreeDefault.tsx
import { useMemo } from 'react';
import { VirtTree } from '@virt-list/react-legacy';
import TreeDefaultItem from './items/TreeDefaultItem';
import TreeEmpty from './items/TreeEmpty';
import '../../demo.css';

function generateTreeData() {
  return Array.from({ length: 40 }, (_, i) => ({
    id: String(i),
    title: `Node-${i}`,
    children: Array.from({ length: 3 }, (_, j) => ({
      id: `${i}-${j}`,
      title: `Node-${i}-${j}`,
      children: Array.from({ length: 2 }, (_, k) => ({
        id: `${i}-${j}-${k}`,
        title: `Node-${i}-${j}-${k}`,
      })),
    })),
  }));
}

export default function TreeDefault() {
  const treeData = useMemo(() => generateTreeData(), []);

  return (
    <div className="tree-demo">
      <div className="virt-tree-wrapper" style={{ width: '100%', height: 400 }}>
        <VirtTree
          list={treeData}
          fieldNames={{ key: 'id' }}
          selectable
          defaultExpandAll
          nodeRender={({ node }) => <TreeDefaultItem node={node} />}
          empty={() => <TreeEmpty />}
        />
      </div>
    </div>
  );
}
