// docs/apps/react/src/components/tree/items/TreeDragItem.tsx
import type { TreeNode } from '@virt-list/react';

export default function TreeDragItem({ node }: { node: TreeNode }) {
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
      <span>{node.isLeaf ? '📄' : '📁'}</span>
      <span>{node.title ?? ''}</span>
    </div>
  );
}

// docs/apps/vue2/src/components/tree/items/TreeDragItem.vue
<template>
  <div style="display: flex; align-items: center; gap: 4px">
    <span>{{ props.node.isLeaf ? '📄' : '📁' }}</span>
    <span>{{ props.node.title ?? '' }}</span>
  </div>
</template>

<script setup lang="ts">
import type { TreeNode } from '@virt-list/vue2';

const props = defineProps<{
  node: TreeNode;
}>();
</script>
