// docs/apps/react/src/components/tree/items/TreeFocusItem.tsx
import type { TreeNode } from '@virt-list/react';

export default function TreeFocusItem({
  node,
  onFocus,
}: {
  node: TreeNode;
  onFocus: (key: TreeNode['key']) => void;
}) {
  return (
    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', width: '100%' }}>
      <span>level: {node.level}; {node.title ?? ''}</span>
      <button
        type="button"
        className="virt-list-btn virt-list-btn-secondary"
        onClick={(e) => {
          e.stopPropagation();
          onFocus(node.key);
        }}
      >
        more
      </button>
    </div>
  );
}

// docs/apps/vue2/src/components/tree/items/TreeFocusItem.vue
<template>
  <div style="display: flex; justify-content: space-between; align-items: center; width: 100%;">
    <span>level: {{ props.node.level }}; {{ props.node.title ?? String(props.node.key) }}</span>
    <button
      type="button"
      class="virt-list-btn virt-list-btn-secondary"
      @click.stop.prevent="emit('focus', props.node.key)"
    >
      more
    </button>
  </div>
</template>

<script setup lang="ts">
import type { TreeNode, TreeNodeKey } from '@virt-list/vue2';

const props = defineProps<{
  node: TreeNode;
}>();

const emit = defineEmits<{
  focus: [key: TreeNodeKey];
}>();
</script>
