// docs/apps/react/src/components/tree/items/TreeDefaultItem.tsx
import type { TreeNode } from '@virt-list/react';

export default function TreeDefaultItem({ node }: { node: TreeNode }) {
  return (
    <div
      style={{
        height: 40,
        display: 'flex',
        alignItems: 'center',
        borderBottom: '1px solid var(--demo-c-divider)',
        boxSizing: 'border-box',
        paddingLeft: 4,
      }}
    >
      level: {node.level}; -- title: {node.title ?? ''}
    </div>
  );
}

// docs/apps/vue2/src/components/tree/items/TreeDefaultItem.vue
<template>
  <div
    style="
      height: 40px;
      display: flex;
      align-items: center;
      border-bottom: 1px solid var(--demo-c-divider);
      box-sizing: border-box;
    "
  >
    level: {{ props.node.level }}; -- title: {{ props.node.title ?? '' }}
  </div>
</template>

<script setup lang="ts">
import type { TreeNode } from '@virt-list/vue2';

const props = defineProps<{
  node: TreeNode;
}>();
</script>
