// docs/apps/vue2/src/components/list/ListKeepAlive.vue
<template>
  <div class="demo-panel">
    <div class="demo-ka-tabs">
      <button
        type="button"
        class="demo-ka-tab"
        :class="{ 'is-active': activeTab === 'users' }"
        @click="activeTab = 'users'"
      >
        用户列表
      </button>
      <button
        type="button"
        class="demo-ka-tab"
        :class="{ 'is-active': activeTab === 'products' }"
        @click="activeTab = 'products'"
      >
        商品列表
      </button>
    </div>
    <div class="demo-ka-toolbar">
      <template v-if="activeTab === 'users'">
        <button type="button" class="virt-list-btn virt-list-btn-primary" @click="addUsers">添加5个用户</button>
        <button type="button" class="virt-list-btn virt-list-btn-warning" @click="clearUsers">清空列表</button>
        <button type="button" class="virt-list-btn virt-list-btn-success" @click="userListRef?.scrollToTop()">
          回到顶部
        </button>
        <button type="button" class="virt-list-btn virt-list-btn-secondary" @click="userListRef?.scrollToBottom()">
          滚动到底部
        </button>
        <span style="font-size: 12px; color: var(--demo-c-text-2); margin-left: 8px">总数: {{ users.length }}</span>
      </template>
      <template v-else>
        <button type="button" class="virt-list-btn virt-list-btn-primary" @click="addProducts">添加5个商品</button>
        <button type="button" class="virt-list-btn virt-list-btn-warning" @click="clearProducts">清空列表</button>
        <button type="button" class="virt-list-btn virt-list-btn-success" @click="productListRef?.scrollToTop()">
          回到顶部
        </button>
        <button type="button" class="virt-list-btn virt-list-btn-secondary" @click="productListRef?.scrollToBottom()">
          滚动到底部
        </button>
        <span style="font-size: 12px; color: var(--demo-c-text-2); margin-left: 8px">总数: {{ products.length }}</span>
      </template>
    </div>
    <div class="demo-list-container" style="height: 500px; position: relative">
      <div
        v-show="activeTab === 'users'"
        style="position: absolute; inset: 0; width: 100%; height: 100%"
      >
        <VirtList
          ref="userListRef"
          :list="users"
          item-key="id"
          :item-pre-size="70"
        >
          <template #default="{ itemData }">
            <div class="demo-ka-card">
              <div class="demo-ka-avatar">{{ itemData.name.charAt(0) }}</div>
              <div class="demo-ka-info">
                <div style="font-weight: bold">{{ itemData.name }}</div>
                <div style="font-size: 11px; color: var(--demo-c-text-2)">{{ itemData.email }} | {{ itemData.department }}</div>
                <div style="font-size: 11px; color: var(--demo-c-text-3)">入职: {{ itemData.joinDate }}</div>
              </div>
            </div>
          </template>
        </VirtList>
      </div>
      <div
        v-show="activeTab === 'products'"
        style="position: absolute; inset: 0; width: 100%; height: 100%"
      >
        <VirtList
          ref="productListRef"
          :list="products"
          item-key="id"
          :item-pre-size="70"
        >
          <template #default="{ itemData }">
            <div class="demo-ka-card">
              <div class="demo-ka-avatar" style="background: var(--demo-c-warning)">{{ itemData.name.charAt(0) }}</div>
              <div class="demo-ka-info">
                <div style="font-weight: bold">
                  {{ itemData.name }}
                  <span style="color: var(--demo-c-danger-text); font-size: 12px">¥{{ itemData.price }}</span>
                </div>
                <div style="font-size: 11px; color: var(--demo-c-text-2)">{{ itemData.category }} | 库存: {{ itemData.stock }}</div>
                <div style="font-size: 11px; color: var(--demo-c-text-3)">{{ itemData.description }}</div>
              </div>
            </div>
          </template>
        </VirtList>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { VirtList } from '@virt-list/vue2';

function generateUsers(count: number) {
  const departments = ['工程部', '设计部', '产品部', '市场部', '运营部'];
  return Array.from({ length: count }, (_, i) => ({
    id: i,
    name: `用户_${i}`,
    email: `user${i}@example.com`,
    department: departments[i % departments.length],
    joinDate: new Date(2020, i % 12, (i % 28) + 1).toLocaleDateString(),
  }));
}

function generateProducts(count: number) {
  const categories = ['电子产品', '家居用品', '食品饮料', '运动户外', '图书文具'];
  return Array.from({ length: count }, (_, i) => ({
    id: i,
    name: `商品_${i}`,
    description: `这是商品 ${i} 的描述信息`,
    price: (Math.random() * 1000).toFixed(2),
    category: categories[i % categories.length],
    stock: Math.floor(Math.random() * 500),
  }));
}

type User = ReturnType<typeof generateUsers>[number];
type Product = ReturnType<typeof generateProducts>[number];

const userListRef = ref<typeof VirtList | null>(null);
const productListRef = ref<typeof VirtList | null>(null);
const activeTab = ref<'users' | 'products'>('users');
const users = ref<User[]>(generateUsers(2000));
const products = ref<Product[]>(generateProducts(2000));

function addUsers() {
  const newUsers = generateUsers(5).map((u, i) => ({
    ...u,
    id: users.value.length + i,
    name: `新用户_${users.value.length + i}`,
  }));
  users.value = users.value.concat(newUsers);
  userListRef.value?.forceUpdate();
}

function clearUsers() {
  users.value = [];
  userListRef.value?.forceUpdate();
}

function addProducts() {
  const newProds = generateProducts(5).map((p, i) => ({
    ...p,
    id: products.value.length + i,
    name: `新商品_${products.value.length + i}`,
  }));
  products.value = products.value.concat(newProds);
  productListRef.value?.forceUpdate();
}

function clearProducts() {
  products.value = [];
  productListRef.value?.forceUpdate();
}
</script>

// docs/apps/react/src/components/list/ListKeepAlive.tsx
import { useRef, useState, useLayoutEffect } from 'react';
import { VirtList, type VirtListRef } from '@virt-list/react';

interface User {
  id: number;
  name: string;
  email: string;
  department: string;
  joinDate: string;
}

interface Product {
  id: number;
  name: string;
  description: string;
  price: string;
  category: string;
  stock: number;
}

function generateUsers(count: number): User[] {
  const departments = ['工程部', '设计部', '产品部', '市场部', '运营部'];
  return Array.from({ length: count }, (_, i) => ({
    id: i,
    name: `用户_${i}`,
    email: `user${i}@example.com`,
    department: departments[i % departments.length]!,
    joinDate: new Date(2020, i % 12, (i % 28) + 1).toLocaleDateString(),
  }));
}

function generateProducts(count: number): Product[] {
  const categories = ['电子产品', '家居用品', '食品饮料', '运动户外', '图书文具'];
  return Array.from({ length: count }, (_, i) => ({
    id: i,
    name: `商品_${i}`,
    description: `这是商品 ${i} 的描述信息`,
    price: (Math.random() * 1000).toFixed(2),
    category: categories[i % categories.length]!,
    stock: Math.floor(Math.random() * 500),
  }));
}

type Tab = 'users' | 'products';

export default function KeepAlive() {
  const userListRef = useRef<VirtListRef<User>>(null);
  const productListRef = useRef<VirtListRef<Product>>(null);
  const [users, setUsers] = useState(() => generateUsers(2000));
  const [products, setProducts] = useState(() => generateProducts(2000));
  const [activeTab, setActiveTab] = useState<Tab>('users');
  const userScrollRef = useRef(0);
  const productScrollRef = useRef(0);

  const switchTab = (tab: Tab) => {
    if (tab === activeTab) return;
    if (activeTab === 'users') {
      userScrollRef.current = userListRef.current?.getOffset() ?? 0;
    } else {
      productScrollRef.current = productListRef.current?.getOffset() ?? 0;
    }
    setActiveTab(tab);
  };

  useLayoutEffect(() => {
    if (activeTab === 'users' && userScrollRef.current > 0) {
      userListRef.current?.scrollToOffset(userScrollRef.current);
    } else if (activeTab === 'products' && productScrollRef.current > 0) {
      productListRef.current?.scrollToOffset(productScrollRef.current);
    }
  }, [activeTab]);

  return (
    <div className="demo-panel">
      <div className="demo-ka-tabs">
        <button
          type="button"
          className={`demo-ka-tab${activeTab === 'users' ? ' is-active' : ''}`}
          onClick={() => switchTab('users')}
        >
          用户列表
        </button>
        <button
          type="button"
          className={`demo-ka-tab${activeTab === 'products' ? ' is-active' : ''}`}
          onClick={() => switchTab('products')}
        >
          商品列表
        </button>
      </div>
      <div className="demo-ka-toolbar">
        {activeTab === 'users' ? (
          <>
            <button type="button" className="virt-list-btn virt-list-btn-primary" onClick={() => {
              const newUsers = generateUsers(5).map((u, i) => ({ ...u, id: users.length + i, name: `新用户_${users.length + i}` }));
              setUsers((prev) => [...prev, ...newUsers]);
            }}>添加5个用户</button>
            <button type="button" className="virt-list-btn virt-list-btn-warning" onClick={() => setUsers([])}>清空列表</button>
            <button type="button" className="virt-list-btn virt-list-btn-success" onClick={() => userListRef.current?.scrollToTop()}>回到顶部</button>
            <button type="button" className="virt-list-btn virt-list-btn-secondary" onClick={() => userListRef.current?.scrollToBottom()}>滚动到底部</button>
            <span style={{ fontSize: 12, color: 'var(--demo-c-text-2)', marginLeft: 8 }}>总数: {users.length}</span>
          </>
        ) : (
          <>
            <button type="button" className="virt-list-btn virt-list-btn-primary" onClick={() => {
              const newProds = generateProducts(5).map((p, i) => ({ ...p, id: products.length + i, name: `新商品_${products.length + i}` }));
              setProducts((prev) => [...prev, ...newProds]);
            }}>添加5个商品</button>
            <button type="button" className="virt-list-btn virt-list-btn-warning" onClick={() => setProducts([])}>清空列表</button>
            <button type="button" className="virt-list-btn virt-list-btn-success" onClick={() => productListRef.current?.scrollToTop()}>回到顶部</button>
            <button type="button" className="virt-list-btn virt-list-btn-secondary" onClick={() => productListRef.current?.scrollToBottom()}>滚动到底部</button>
            <span style={{ fontSize: 12, color: 'var(--demo-c-text-2)', marginLeft: 8 }}>总数: {products.length}</span>
          </>
        )}
      </div>
      <div className="demo-list-container" style={{ height: 500 }}>
        {activeTab === 'users' ? (
          <VirtList
            ref={userListRef}
            list={users}
            itemKey="id"
            itemPreSize={70}
          >
            {({ itemData: user }) => (
              <div className="demo-ka-card">
                <div className="demo-ka-avatar">{user.name.charAt(0)}</div>
                <div className="demo-ka-info">
                  <div style={{ fontWeight: 'bold' }}>{user.name}</div>
                  <div style={{ fontSize: 11, color: 'var(--demo-c-text-2)' }}>{user.email} | {user.department}</div>
                  <div style={{ fontSize: 11, color: 'var(--demo-c-text-3)' }}>入职: {user.joinDate}</div>
                </div>
              </div>
            )}
          </VirtList>
        ) : (
          <VirtList
            ref={productListRef}
            list={products}
            itemKey="id"
            itemPreSize={70}
          >
            {({ itemData: product }) => (
              <div className="demo-ka-card">
                <div className="demo-ka-avatar" style={{ background: 'var(--demo-c-warning)' }}>{product.name.charAt(0)}</div>
                <div className="demo-ka-info">
                  <div style={{ fontWeight: 'bold' }}>{product.name} <span style={{ color: 'var(--demo-c-danger-text)', fontSize: 12 }}>¥{product.price}</span></div>
                  <div style={{ fontSize: 11, color: 'var(--demo-c-text-2)' }}>{product.category} | 库存: {product.stock}</div>
                  <div style={{ fontSize: 11, color: 'var(--demo-c-text-3)' }}>{product.description}</div>
                </div>
              </div>
            )}
          </VirtList>
        )}
      </div>
    </div>
  );
}
