// docs/apps/react/src/components/tree/TreeFocus.tsx
import { useRef, useState, useMemo } from 'react';
import { VirtTree, type VirtTreeRef } from '@virt-list/react';
import TreeFocusItem from './items/TreeFocusItem';
import TreeEmpty from './items/TreeEmpty';
import '../../demo.css';

function generateTreeData() {
  return Array.from({ length: 40 }, (_, i) => ({
    id: String(i),
    title: `Node-${i}`,
    children: Array.from({ length: 3 }, (_, j) => ({
      id: `${i}-${j}`,
      title: `Node-${i}-${j}`,
      children: Array.from({ length: 2 }, (_, k) => ({
        id: `${i}-${j}-${k}`,
        title: `Node-${i}-${j}-${k}`,
      })),
    })),
  }));
}

export default function TreeFocus() {
  const treeRef = useRef<VirtTreeRef>(null);
  const [focusedKeys, setFocusedKeys] = useState<string[]>([]);
  const treeData = useMemo(() => generateTreeData(), []);

  return (
    <div className="tree-demo">
      <div className="status-text" style={{ margin: '8px 0', minHeight: 24 }}>
        focusedKeys: [{focusedKeys.join(', ')}]
      </div>
      <div className="virt-tree-wrapper" style={{ width: '100%', height: 400 }}>
        <VirtTree
          ref={treeRef}
          list={treeData}
          fieldNames={{ key: 'id' }}
          selectable
          defaultExpandAll
          content={({ node }) => (
            <TreeFocusItem
              node={node}
              onFocus={(key) => {
                treeRef.current?.setFocusedKeys([key]);
                setFocusedKeys([String(key)]);
              }}
            />
          )}
          empty={() => <TreeEmpty />}
        />
      </div>
    </div>
  );
}

// docs/apps/vue2/src/components/tree/TreeFocus.vue
<template>
  <div class="tree-demo">
    <div class="status-text" style="margin-bottom: 8px">
      focusedKeys: [{{ focusedKeys.join(', ') }}]
    </div>
    <div class="virt-tree-wrapper">
      <VirtTree
        :list="treeData"
        :field-names="{ key: 'id' }"
        :indent="20"
        selectable
        default-expand-all
        :focused-keys="focusedKeys"
      >
        <template #content="{ node }">
          <TreeFocusItem :node="node" @focus="(key) => (focusedKeys = [key])" />
        </template>
        <template #empty>
          <TreeEmpty />
        </template>
      </VirtTree>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { VirtTree } from '@virt-list/vue2';
import type { TreeNodeKey } from '@virt-list/vue2';
import TreeFocusItem from './items/TreeFocusItem.vue';
import TreeEmpty from './items/TreeEmpty.vue';
import '../../demo.css';

function generateTreeData() {
  return Array.from({ length: 40 }, (_, i) => ({
    id: String(i),
    title: `Node-${i}`,
    children: Array.from({ length: 3 }, (_, j) => ({
      id: `${i}-${j}`,
      title: `Node-${i}-${j}`,
      children: Array.from({ length: 2 }, (_, k) => ({
        id: `${i}-${j}-${k}`,
        title: `Node-${i}-${j}-${k}`,
      })),
    })),
  }));
}

const treeData = ref(generateTreeData());
const focusedKeys = ref<TreeNodeKey[]>([]);
</script>
