// docs/apps/react-legacy/src/components/list/ListHorizontal.tsx
import { useState, useMemo } from 'react';
import { VirtList } from '@virt-list/react-legacy';
import '../../demo.css';

const WIDTHS = [60, 80, 100, 110, 130];

interface Item {
  id: number;
  width: number;
}

function generateList(count: number): Item[] {
  return Array.from({ length: count }, (_, i) => ({
    id: i,
    width: WIDTHS[Math.floor(Math.random() * WIDTHS.length)],
  }));
}

export default function Horizontal() {
  const list = useMemo(() => generateList(1000), []);
  const [stats, setStats] = useState(`总数: ${list.length} | 水平滚动`);

  return (
    <div className="demo-panel">
      <div className="demo-stats">{stats}</div>
      <div className="demo-horizontal-container">
        <VirtList<Item>
          list={list}
          itemKey="id"
          itemPreSize={60}
          horizontal
          onUpdate={(_, state) =>
            setStats(`总数: ${list.length} | 可视区域: ${state.inViewBegin} - ${state.inViewEnd} | 渲染区间: ${state.renderBegin} - ${state.renderEnd}`)
          }
        >
          {({ itemData }) => (
            <div
              className="demo-col-item"
              style={{ minWidth: itemData.width, width: itemData.width }}
            >
              <div style={{ fontWeight: 'bold' }}>{itemData.id}</div>
              <div style={{ fontSize: 11, color: '#999' }}>w:{itemData.width}</div>
            </div>
          )}
        </VirtList>
      </div>
    </div>
  );
}

// docs/apps/vue/src/components/list/ListHorizontal.vue
<template>
  <div class="demo-panel">
    <div class="demo-stats">{{ statsText }}</div>
    <div class="demo-horizontal-container">
      <VirtList
        :list="list"
        item-key="id"
        :item-pre-size="60"
        horizontal
        @update="onUpdate"
      >
        <template #default="{ itemData }">
          <div
            class="demo-col-item"
            :style="{ minWidth: `${itemData.width}px`, width: `${itemData.width}px` }"
          >
            <div style="font-weight: bold">{{ itemData.id }}</div>
            <div style="font-size: 11px; color: #999">w:{{ itemData.width }}</div>
          </div>
        </template>
      </VirtList>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { VirtList } from '@virt-list/vue';
import '../../demo.css';

const WIDTHS = [60, 80, 100, 110, 130];

function generateList(count: number) {
  return Array.from({ length: count }, (_, i) => ({
    id: i,
    width: WIDTHS[Math.floor(Math.random() * WIDTHS.length)]!,
  }));
}

type Item = ReturnType<typeof generateList>[number];

const statsText = ref('');
const list = ref<Item[]>(generateList(1000));

statsText.value = `总数: ${list.value.length} | 水平滚动`;

function onUpdate(_list: any[], state: any) {
  statsText.value = `总数: ${list.value.length} | 可视区域: ${state.inViewBegin} - ${state.inViewEnd} | 渲染区间: ${state.renderBegin} - ${state.renderEnd}`;
}
</script>
