// docs/apps/react-legacy/src/components/Literal.tsx
import { faker } from '@faker-js/faker';
import { useEffect, useRef } from 'react';
import { VirtList } from '@virt-list/vanilla';

interface DemoItem {
  id: number;
  content: string;
}

function Literal() {
  const containerRef = useRef<HTMLDivElement | null>(null);
  const virtListRef = useRef<VirtList<DemoItem> | null>(null);

  const generateData = (): DemoItem[] => {
    const data: DemoItem[] = [];
    for (let i = 0; i < 100; i += 1) {
      data.push({
        id: i,
        content: faker.lorem.paragraph(),
      });
    }
    return data;
  };

  useEffect(() => {
    const initVirtList = (): void => {
      const container = containerRef.current;
      if (!container) return;

      if (virtListRef.current) {
        virtListRef.current.destroy();
      }

      virtListRef.current = new VirtList(container, {
        list: generateData(),
        itemKey: 'id',
        itemPreSize: 50,
        renderItem: (item: DemoItem): HTMLElement => {
          const row = document.createElement('div');
          row.style.padding = '4px';
          row.innerHTML = `
            <div style="font-weight:bold;">Item ${item.id}</div>
            <div style="color:var(--demo-c-text-2);font-size:12px;">${item.content}</div>
            <div style="color:var(--demo-c-text-3);font-size:10px;">Key: ${item.id} (DOM)</div>
          `;
          return row;
        },
      });
    };

    initVirtList();
    return () => {
      if (virtListRef.current) {
        virtListRef.current.destroy();
      }
      virtListRef.current = null;
    };
  }, []);

  return (
    <div style={{ maxWidth: 800, margin: '0 auto', padding: 20 }}>
      <div
        ref={containerRef}
        style={{
          width: 400,
          height: 600,
          border: '1px solid var(--demo-c-border-strong)',
          margin: '20px auto',
        }}
      />
    </div>
  );
}

export default Literal;

// docs/apps/vue/src/components/Literal.vue
<template>
  <div style="max-width: 800px; margin: 0 auto; padding: 20px">
    <div
      ref="container"
      style="
        width: 400px;
        height: 600px;
        border: 1px solid var(--demo-c-border-strong);
        margin: 20px auto;
      "
    />
  </div>
</template>

<script setup lang="ts">
import { onMounted, onUnmounted, ref } from 'vue';
import { VirtList } from '@virt-list/vanilla';
import { faker } from '@faker-js/faker';

interface DemoItem {
  id: number;
  content: string;
}

const container = ref<HTMLElement | null>(null);
let virtList: VirtList<DemoItem> | null = null;

const generateData = (): DemoItem[] => {
  const data: DemoItem[] = [];
  for (let i = 0; i < 100; i += 1) {
    data.push({
      id: i,
      content: faker.lorem.paragraph(),
    });
  }
  return data;
};

const initVirtList = (): void => {
  if (!container.value) return;

  if (virtList) {
    virtList.destroy();
  }

  virtList = new VirtList(container.value, {
    list: generateData(),
    itemKey: 'id',
    itemPreSize: 50,
    renderItem: (item: DemoItem): HTMLElement => {
      const row = document.createElement('div');
      row.style.padding = '4px';
      row.innerHTML = `
        <div style="font-weight:bold;">Item ${item.id}</div>
        <div style="color:var(--demo-c-text-2);font-size:12px;">${item.content}</div>
        <div style="color:var(--demo-c-text-3);font-size:10px;">Key: ${item.id} (DOM)</div>
      `;
      return row;
    },
  });
};

onMounted(() => {
  initVirtList();
});

onUnmounted(() => {
  if (virtList) {
    virtList.destroy();
    virtList = null;
  }
});
</script>
