// docs/apps/vue/src/App.tsx
import { defineComponent } from 'vue';
import DemoBlock from './components/DemoBlock.vue';
import Literal from './components/Literal.vue';
import Widget from './components/Widget.vue';

import Basic from './components/list/Basic.vue';
import Buffer from './components/list/Buffer.vue';
import HugeData from './components/list/HugeData.vue';
import Fixed from './components/list/Fixed.vue';
import Horizontal from './components/list/Horizontal.vue';
import Slots from './components/list/Slots.vue';
import Operations from './components/list/Operations.vue';
import Resize from './components/list/Resize.vue';
import Dynamic from './components/list/Dynamic.vue';
import Table from './components/list/Table.vue';
import Infinity from './components/list/Infinity.vue';
import Chat from './components/list/Chat.vue';
import Advanced from './components/list/Advanced.vue';
import Pagination from './components/list/Pagination.vue';
import KeepAlive from './components/list/KeepAlive.vue';
import Empty from './components/list/Empty.vue';
import Reactive from './components/list/Reactive.vue';

import TreeBasic from './components/tree/TreeBasic.vue';
import TreeExpand from './components/tree/TreeExpand.vue';
import TreeCheckbox from './components/tree/TreeCheckbox.vue';
import TreeSelect from './components/tree/TreeSelect.vue';
import TreeFilter from './components/tree/TreeFilter.vue';
import TreeContent from './components/tree/TreeContent.vue';
import TreeShowLine from './components/tree/TreeShowLine.vue';
import TreeDrag from './components/tree/TreeDrag.vue';
import TreeFocus from './components/tree/TreeFocus.vue';
import TreeOperate from './components/tree/TreeOperate.vue';
import TreeSlots from './components/tree/TreeSlots.vue';
import TreeIcon from './components/tree/TreeIcon.vue';
import TreeDefault from './components/tree/TreeDefault.vue';
import TreeDragArea from './components/tree/TreeDragArea.vue';

import VirtGrid from './components/grid/VirtGrid.vue';

const rawSources = import.meta.glob(
  ['./components/list/*.vue', './components/tree/*.vue', './components/grid/*.vue'],
  { query: '?raw', import: 'default', eager: true },
) as Record<string, string>;

function src(path: string): string {
  return rawSources[path] ?? '';
}

type FrameworkKind = 'react' | 'vue';

export default defineComponent({
  name: 'VueTsxDemo',
  props: {
    exampleId: {
      type: String,
      default: '',
    },
    onEvent: {
      type: Function as unknown as () => ((payload: { framework: FrameworkKind; message: string }) => void) | undefined,
      default: undefined,
    },
  },
  setup(props) {
    const demoRenderMap: Record<string, () => JSX.Element> = {
      'literal': () => <Literal />,
      'widget': () => <Widget />,
      'basic': () => <DemoBlock source={src('./components/list/Basic.vue')}><Basic /></DemoBlock>,
      'buffer': () => <DemoBlock source={src('./components/list/Buffer.vue')}><Buffer /></DemoBlock>,
      'huge-data': () => <DemoBlock source={src('./components/list/HugeData.vue')}><HugeData /></DemoBlock>,
      'fixed': () => <DemoBlock source={src('./components/list/Fixed.vue')}><Fixed /></DemoBlock>,
      'horizontal': () => <DemoBlock source={src('./components/list/Horizontal.vue')}><Horizontal /></DemoBlock>,
      'slots': () => <DemoBlock source={src('./components/list/Slots.vue')}><Slots /></DemoBlock>,
      'operations': () => <DemoBlock source={src('./components/list/Operations.vue')}><Operations /></DemoBlock>,
      'resize': () => <DemoBlock source={src('./components/list/Resize.vue')}><Resize /></DemoBlock>,
      'dynamic': () => <DemoBlock source={src('./components/list/Dynamic.vue')}><Dynamic /></DemoBlock>,
      'table': () => <DemoBlock source={src('./components/list/Table.vue')}><Table /></DemoBlock>,
      'infinity': () => <DemoBlock source={src('./components/list/Infinity.vue')}><Infinity /></DemoBlock>,
      'chat': () => <DemoBlock source={src('./components/list/Chat.vue')}><Chat /></DemoBlock>,
      'advanced': () => <DemoBlock source={src('./components/list/Advanced.vue')}><Advanced /></DemoBlock>,
      'pagination': () => <DemoBlock source={src('./components/list/Pagination.vue')}><Pagination /></DemoBlock>,
      'keep-alive': () => <DemoBlock source={src('./components/list/KeepAlive.vue')}><KeepAlive /></DemoBlock>,
      'empty': () => <DemoBlock source={src('./components/list/Empty.vue')}><Empty /></DemoBlock>,
      'reactive': () => <DemoBlock source={src('./components/list/Reactive.vue')}><Reactive /></DemoBlock>,
      'virt-tree-basic': () => <DemoBlock source={src('./components/tree/TreeBasic.vue')}><TreeBasic /></DemoBlock>,
      'virt-tree-expand': () => <DemoBlock source={src('./components/tree/TreeExpand.vue')}><TreeExpand /></DemoBlock>,
      'virt-tree-checkbox': () => <DemoBlock source={src('./components/tree/TreeCheckbox.vue')}><TreeCheckbox /></DemoBlock>,
      'virt-tree-select': () => <DemoBlock source={src('./components/tree/TreeSelect.vue')}><TreeSelect /></DemoBlock>,
      'virt-tree-filter': () => <DemoBlock source={src('./components/tree/TreeFilter.vue')}><TreeFilter /></DemoBlock>,
      'virt-tree-content': () => <DemoBlock source={src('./components/tree/TreeContent.vue')}><TreeContent /></DemoBlock>,
      'virt-tree-showline': () => <DemoBlock source={src('./components/tree/TreeShowLine.vue')}><TreeShowLine /></DemoBlock>,
      'virt-tree-drag': () => <DemoBlock source={src('./components/tree/TreeDrag.vue')}><TreeDrag /></DemoBlock>,
      'virt-tree-focus': () => <DemoBlock source={src('./components/tree/TreeFocus.vue')}><TreeFocus /></DemoBlock>,
      'virt-tree-operate': () => <DemoBlock source={src('./components/tree/TreeOperate.vue')}><TreeOperate /></DemoBlock>,
      'virt-tree-slots': () => <DemoBlock source={src('./components/tree/TreeSlots.vue')}><TreeSlots /></DemoBlock>,
      'virt-tree-icon': () => <DemoBlock source={src('./components/tree/TreeIcon.vue')}><TreeIcon /></DemoBlock>,
      'virt-tree-default': () => <DemoBlock source={src('./components/tree/TreeDefault.vue')}><TreeDefault /></DemoBlock>,
      'virt-tree-dragarea': () => <DemoBlock source={src('./components/tree/TreeDragArea.vue')}><TreeDragArea /></DemoBlock>,
      'virt-grid': () => <DemoBlock source={src('./components/grid/VirtGrid.vue')}><VirtGrid /></DemoBlock>,
    };

    const renderCurrentDemo = () => {
      const renderer =
        demoRenderMap[props.exampleId as keyof typeof demoRenderMap] ?? demoRenderMap['literal'];
      return renderer();
    };

    return () => (
      renderCurrentDemo()
    );
  },
});

// docs/apps/react/src/App.tsx
import '@arco-design/web-react/dist/css/arco.css';
import DemoBlock from './components/DemoBlock.tsx';
import Literal from './components/Literal.tsx';
import Widget from './components/Widget.tsx';

import Basic from './components/list/Basic.tsx';
import Buffer from './components/list/Buffer.tsx';
import HugeData from './components/list/HugeData.tsx';
import Fixed from './components/list/Fixed.tsx';
import Horizontal from './components/list/Horizontal.tsx';
import Slots from './components/list/Slots.tsx';
import Operations from './components/list/Operations.tsx';
import Resize from './components/list/Resize.tsx';
import Dynamic from './components/list/Dynamic.tsx';
import Table from './components/list/Table.tsx';
import Infinity from './components/list/Infinity.tsx';
import Chat from './components/list/Chat.tsx';
import Advanced from './components/list/Advanced.tsx';
import Pagination from './components/list/Pagination.tsx';
import KeepAlive from './components/list/KeepAlive.tsx';
import Empty from './components/list/Empty.tsx';
import Reactive from './components/list/Reactive.tsx';

import TreeBasic from './components/tree/TreeBasic.tsx';
import TreeExpand from './components/tree/TreeExpand.tsx';
import TreeCheckbox from './components/tree/TreeCheckbox.tsx';
import TreeSelect from './components/tree/TreeSelect.tsx';
import TreeFilter from './components/tree/TreeFilter.tsx';
import TreeContent from './components/tree/TreeContent.tsx';
import TreeShowLine from './components/tree/TreeShowLine.tsx';
import TreeDrag from './components/tree/TreeDrag.tsx';
import TreeFocus from './components/tree/TreeFocus.tsx';
import TreeOperate from './components/tree/TreeOperate.tsx';
import TreeSlots from './components/tree/TreeSlots.tsx';
import TreeIcon from './components/tree/TreeIcon.tsx';
import TreeDefault from './components/tree/TreeDefault.tsx';
import TreeDragArea from './components/tree/TreeDragArea.tsx';

import VirtGrid from './components/grid/VirtGrid.tsx';

const rawSources = import.meta.glob(
  ['./components/list/*.tsx', './components/tree/*.tsx', './components/grid/*.tsx'],
  { query: '?raw', import: 'default', eager: true },
) as Record<string, string>;

function src(path: string): string {
  return rawSources[path] ?? '';
}

interface AppProps {
  exampleId?: string;
  onEvent?: (message: string) => void;
}

const demoRenderMap: Record<string, () => JSX.Element> = {
  'literal': () => <Literal />,
  'widget': () => <Widget />,
  'basic': () => <DemoBlock source={src('./components/list/Basic.tsx')}><Basic /></DemoBlock>,
  'buffer': () => <DemoBlock source={src('./components/list/Buffer.tsx')}><Buffer /></DemoBlock>,
  'huge-data': () => <DemoBlock source={src('./components/list/HugeData.tsx')}><HugeData /></DemoBlock>,
  'fixed': () => <DemoBlock source={src('./components/list/Fixed.tsx')}><Fixed /></DemoBlock>,
  'horizontal': () => <DemoBlock source={src('./components/list/Horizontal.tsx')}><Horizontal /></DemoBlock>,
  'slots': () => <DemoBlock source={src('./components/list/Slots.tsx')}><Slots /></DemoBlock>,
  'operations': () => <DemoBlock source={src('./components/list/Operations.tsx')}><Operations /></DemoBlock>,
  'resize': () => <DemoBlock source={src('./components/list/Resize.tsx')}><Resize /></DemoBlock>,
  'dynamic': () => <DemoBlock source={src('./components/list/Dynamic.tsx')}><Dynamic /></DemoBlock>,
  'table': () => <DemoBlock source={src('./components/list/Table.tsx')}><Table /></DemoBlock>,
  'infinity': () => <DemoBlock source={src('./components/list/Infinity.tsx')}><Infinity /></DemoBlock>,
  'chat': () => <DemoBlock source={src('./components/list/Chat.tsx')}><Chat /></DemoBlock>,
  'advanced': () => <DemoBlock source={src('./components/list/Advanced.tsx')}><Advanced /></DemoBlock>,
  'pagination': () => <DemoBlock source={src('./components/list/Pagination.tsx')}><Pagination /></DemoBlock>,
  'keep-alive': () => <DemoBlock source={src('./components/list/KeepAlive.tsx')}><KeepAlive /></DemoBlock>,
  'empty': () => <DemoBlock source={src('./components/list/Empty.tsx')}><Empty /></DemoBlock>,
  'reactive': () => <DemoBlock source={src('./components/list/Reactive.tsx')}><Reactive /></DemoBlock>,
  'virt-tree-basic': () => <DemoBlock source={src('./components/tree/TreeBasic.tsx')}><TreeBasic /></DemoBlock>,
  'virt-tree-expand': () => <DemoBlock source={src('./components/tree/TreeExpand.tsx')}><TreeExpand /></DemoBlock>,
  'virt-tree-checkbox': () => <DemoBlock source={src('./components/tree/TreeCheckbox.tsx')}><TreeCheckbox /></DemoBlock>,
  'virt-tree-select': () => <DemoBlock source={src('./components/tree/TreeSelect.tsx')}><TreeSelect /></DemoBlock>,
  'virt-tree-filter': () => <DemoBlock source={src('./components/tree/TreeFilter.tsx')}><TreeFilter /></DemoBlock>,
  'virt-tree-content': () => <DemoBlock source={src('./components/tree/TreeContent.tsx')}><TreeContent /></DemoBlock>,
  'virt-tree-showline': () => <DemoBlock source={src('./components/tree/TreeShowLine.tsx')}><TreeShowLine /></DemoBlock>,
  'virt-tree-drag': () => <DemoBlock source={src('./components/tree/TreeDrag.tsx')}><TreeDrag /></DemoBlock>,
  'virt-tree-focus': () => <DemoBlock source={src('./components/tree/TreeFocus.tsx')}><TreeFocus /></DemoBlock>,
  'virt-tree-operate': () => <DemoBlock source={src('./components/tree/TreeOperate.tsx')}><TreeOperate /></DemoBlock>,
  'virt-tree-slots': () => <DemoBlock source={src('./components/tree/TreeSlots.tsx')}><TreeSlots /></DemoBlock>,
  'virt-tree-icon': () => <DemoBlock source={src('./components/tree/TreeIcon.tsx')}><TreeIcon /></DemoBlock>,
  'virt-tree-default': () => <DemoBlock source={src('./components/tree/TreeDefault.tsx')}><TreeDefault /></DemoBlock>,
  'virt-tree-dragarea': () => <DemoBlock source={src('./components/tree/TreeDragArea.tsx')}><TreeDragArea /></DemoBlock>,
  'virt-grid': () => <DemoBlock source={src('./components/grid/VirtGrid.tsx')}><VirtGrid /></DemoBlock>,
};

function App({ exampleId = '' }: AppProps) {
  const renderCurrentDemo = () => {
    const renderer =
      demoRenderMap[exampleId as keyof typeof demoRenderMap] ?? demoRenderMap['literal'];
    return renderer();
  };

  return (
    renderCurrentDemo()
  );
}

export default App;
