// docs/apps/vue/src/components/Widget.vue
<template>
  <div style="max-width: 800px; margin: 0 auto; padding: 20px">
    <div
      style="
        display: flex;
        gap: 10px;
        justify-content: center;
        flex-wrap: wrap;
        margin-bottom: 20px;
      "
    >
      <button @click="scrollToTop">滚动到顶部</button>
      <button @click="scrollToBottom">滚动到底部</button>
      <button @click="scrollToIndex(500)">滚动到第500项</button>
      <button @click="scrollToIndex(Math.floor(Math.random() * 1000))">
        随机滚动
      </button>
    </div>

    <div
      style="
        width: 400px;
        height: 600px;
        border: 1px solid var(--demo-c-border-strong);
        margin: 0 auto;
      "
    >
      <VirtList
        ref="virtListRef"
        :list="list"
        item-key="id"
        :min-size="50"
        @toTop="onToTop"
        @toBottom="onToBottom"
      >
        <template #default="{ itemData, index }">
          <div style="padding: 4px">
            <div style="font-weight: bold">Item {{ itemData.id }}</div>
            <div style="color: var(--demo-c-text-2); font-size: 12px">
              {{ itemData.content }}
            </div>
            <div style="color: var(--demo-c-text-3); font-size: 10px">
              Index: {{ index }} (@virt-list/vue VirtList)
            </div>
          </div>
        </template>
        <template #stickyHeader>
          <div
            style="
              background: var(--demo-c-brand-soft);
              padding: 10px;
              text-align: center;
              font-weight: bold;
            "
          >
            Sticky Header
          </div>
        </template>
        <template #stickyFooter>
          <div
            style="
              background: var(--demo-c-brand-soft);
              padding: 10px;
              text-align: center;
              font-weight: bold;
            "
          >
            Sticky Footer
          </div>
        </template>
      </VirtList>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { faker } from '@faker-js/faker';
import { VirtList } from '@virt-list/vue';

interface DemoItem {
  id: number;
  content: string;
}

const virtListRef = ref<typeof VirtList | null>(null);

const list: DemoItem[] = Array.from({ length: 1000 }, (_, i) => ({
  id: i,
  content: faker.lorem.paragraph(),
}));

const scrollToTop = () => (virtListRef.value as any)?.scrollToTop();
const scrollToBottom = () => (virtListRef.value as any)?.scrollToBottom();
const scrollToIndex = (index: number) =>
  (virtListRef.value as any)?.scrollToIndex(index);
const onToTop = (item: DemoItem) => console.log('到达顶部', item);
const onToBottom = (item: DemoItem) => console.log('到达底部', item);
</script>

// docs/apps/react/src/components/Widget.tsx
import { faker } from '@faker-js/faker';
import { useMemo, useRef } from 'react';
import { VirtList, type VirtListRef } from '@virt-list/react';

interface DemoItem {
  id: number;
  content: string;
}

function VirtListDemo() {
  const virtListRef = useRef<VirtListRef<DemoItem>>(null);

  const list = useMemo<DemoItem[]>(() => {
    return Array.from({ length: 1000 }, (_, i) => ({
      id: i,
      content: faker.lorem.paragraph(),
    }));
  }, []);

  return (
    <div style={{ maxWidth: 800, margin: '0 auto', padding: 20 }}>
      <div
        style={{
          display: 'flex',
          gap: 10,
          justifyContent: 'center',
          flexWrap: 'wrap',
          marginBottom: 20,
        }}
      >
        <button onClick={() => virtListRef.current?.scrollToTop()}>
          滚动到顶部
        </button>
        <button onClick={() => virtListRef.current?.scrollToBottom()}>
          滚动到底部
        </button>
        <button onClick={() => virtListRef.current?.scrollToIndex(500)}>
          滚动到第500项
        </button>
        <button onClick={() => virtListRef.current?.scrollToIndex(Math.floor(Math.random() * 1000))}>
          随机滚动
        </button>
      </div>

      <div
        style={{
          width: 400,
          height: 600,
          border: '1px solid var(--demo-c-border-strong)',
          margin: '0 auto',
        }}
      >
        <VirtList
          ref={virtListRef}
          list={list}
          itemKey="id"
          itemPreSize={50}
          renderStickyHeader={() => (
            <div
              style={{
                background: 'var(--demo-c-brand-soft)',
                padding: 10,
                textAlign: 'center',
                fontWeight: 'bold',
              }}
            >
              Sticky Header
            </div>
          )}
          renderStickyFooter={() => (
            <div
              style={{
                background: 'var(--demo-c-brand-soft)',
                padding: 10,
                textAlign: 'center',
                fontWeight: 'bold',
              }}
            >
              Sticky Footer
            </div>
          )}
          onToTop={(item) => console.log('到达顶部', item)}
          onToBottom={(item) => console.log('到达底部', item)}
        >
          {({ itemData, index }) => (
            <div style={{ padding: 4 }}>
              <div style={{ fontWeight: 'bold' }}>Item {itemData.id}</div>
              <div style={{ color: 'var(--demo-c-text-2)', fontSize: 12 }}>{itemData.content}</div>
              <div style={{ color: 'var(--demo-c-text-3)', fontSize: 10 }}>
                Index: {index} (@virt-list/react VirtList)
              </div>
            </div>
          )}
        </VirtList>
      </div>
    </div>
  );
}

export default VirtListDemo;
