// docs/apps/vue2/src/components/grid/GridItem.vue
<template>
  <div class="grid-cell">
    <div>
      <div style="font-size:12px;color:var(--demo-c-text-3);">
        row:{{ rowIndex }} - item:{{ listIndex }}
      </div>
      <div style="display:flex;align-items:center;">
        <img :src="item.avatar" style="width:40px;height:40px;border-radius:50%;" />
        <span style="margin-left:6px;">{{ item.name }}</span>
      </div>
    </div>
    <button class="grid-delete-btn" @click="emit('delete')">delete</button>
  </div>
</template>

<script setup lang="ts">
defineProps<{
  item: {
    id: string;
    avatar: string;
    name: string;
  };
  listIndex: number;
  rowIndex: number;
}>();

const emit = defineEmits<{
  (e: 'delete'): void;
}>();
</script>

// docs/apps/react-legacy/src/components/grid/GridItem.tsx
type GridItemData = {
  id: string;
  avatar: string;
  name: string;
};

type GridItemProps = {
  item: GridItemData;
  listIndex: number;
  rowIndex: number;
  onDelete: () => void;
};

export function GridItem(props: GridItemProps) {
  const { item, listIndex, rowIndex, onDelete } = props;
  return (
    <div className="grid-cell">
      <div>
        <div style={{ fontSize: 12, color: 'var(--demo-c-text-3)' }}>{`row:${rowIndex} - item:${listIndex}`}</div>
        <div style={{ display: 'flex', alignItems: 'center' }}>
          <img src={item.avatar} style={{ width: 40, height: 40, borderRadius: '50%' }} />
          <span style={{ marginLeft: 6 }}>{item.name}</span>
        </div>
      </div>
      <button className="grid-delete-btn" onClick={onDelete}>delete</button>
    </div>
  );
}
