// docs/apps/vue/src/components/grid/GridBasic.vue
<template>
  <div class="virt-grid-demo">
    <div class="virt-grid-controls">
      <span>gridItems:</span>
      <button type="button" class="virt-list-btn virt-list-btn-primary" @click="setGridItems(2)">2</button>
      <button type="button" class="virt-list-btn virt-list-btn-primary" @click="setGridItems(3)">3</button>
      <button type="button" class="virt-list-btn virt-list-btn-primary" @click="setGridItems(4)">4</button>
      <button type="button" class="virt-list-btn virt-list-btn-primary" @click="setGridItems(5)">5</button>
      <button type="button" class="virt-list-btn virt-list-btn-primary" @click="setGridItems(6)">6</button>
    </div>
    <div class="status-text">{{ statusText }}</div>
    <div class="virt-grid-container">
      <VirtGrid
        ref="gridRef"
        :list="gridList"
        :grid-items="gridItems"
        item-key="id"
        :item-pre-size="70"
        @to-top="onToTop"
      >
        <template #default="{ itemData, index, rowIndex }">
          <GridItem
            :item="itemData"
            :index="index"
            :row-index="rowIndex"
            @delete="handleDelete(itemData, index)"
          />
        </template>
      </VirtGrid>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { faker } from '@faker-js/faker';
import { VirtGrid } from '@virt-list/vue';
import GridItem from './GridItem.vue';
import type { VirtGridRef } from '../_virtRefTypes';
import '../../demo.css';

function generateData(count: number) {
  return Array.from({ length: count }, (_, i) => ({
    id: faker.string.nanoid(),
    index: i,
    avatar: faker.image.avatar(),
    name: faker.person.firstName(),
  }));
}

type GridItem = ReturnType<typeof generateData>[number];

const gridRef = ref<VirtGridRef | null>(null);
const statusText = ref('');
const gridItems = ref(2);
const gridList = ref<GridItem[]>(generateData(1000));

function handleDelete(item: GridItem, index: number) {
  const idx = gridList.value.findIndex((v) => v.id === item.id);
  if (idx > -1) {
    gridList.value = gridList.value.filter((v) => v.id !== item.id);
    statusText.value = `已删除 item ${index}，剩余 ${gridList.value.length} 项`;
  }
}

statusText.value = '网格示例已就绪：1000 项数据，2 列';

function setGridItems(n: number) {
  gridItems.value = n;
  gridRef.value?.setGridItems(n);
  statusText.value = `gridItems 已设为 ${n}`;
}

function onToTop() {
  statusText.value = '已滚动到顶部';
}
</script>

// docs/apps/react/src/components/grid/GridBasic.tsx
import { useRef, useState } from 'react';
import { faker } from '@faker-js/faker';
import { VirtGrid as VirtGridRoot, type VirtGridRef } from '@virt-list/react';
import { GridItem } from './GridItem';
import '../../demo.css';

function generateData(count: number) {
  return Array.from({ length: count }, (_, i) => ({
    id: faker.string.nanoid(),
    index: i,
    avatar: faker.image.avatar(),
    name: faker.person.firstName(),
  }));
}

export default function VirtGrid() {
  const [list, setList] = useState(() => generateData(1000));
  const [status, setStatus] = useState('网格示例已就绪：1000 项数据，2 列');
  const gridRef = useRef<VirtGridRef>(null);

  const setGridItems = (n: number) => {
    gridRef.current?.setGridItems(n);
    setStatus(`gridItems 已设为 ${n}`);
  };

  return (
    <div className="virt-grid-demo">
      <div className="virt-grid-controls">
        <span>gridItems:</span>
        {[2, 3, 4, 5, 6].map((n) => (
          <button key={n} type="button" className="virt-list-btn virt-list-btn-primary" onClick={() => setGridItems(n)}>
            {n}
          </button>
        ))}
      </div>
      <div className="status-text">{status}</div>
      <div className="virt-grid-container" style={{ width: '100%', height: 500 }}>
        <VirtGridRoot
          ref={gridRef}
          list={list}
          gridItems={2}
          itemKey="id"
          itemPreSize={70}
          onToTop={() => {
            setStatus('已滚动到顶部');
          }}
        >
          {({ itemData, index, rowIndex }) => (
            <GridItem
              item={itemData as (typeof list)[number]}
              index={index}
              rowIndex={rowIndex}
              onDelete={() => {
                const id = itemData.id;
                setList((prev) => {
                  const idx = prev.findIndex((v) => v.id === id);
                  if (idx > -1) {
                    const next = prev.slice();
                    next.splice(idx, 1);
                    setStatus(`已删除 item ${index}，剩余 ${next.length} 项`);
                    return next;
                  }
                  return prev;
                });
              }}
            />
          )}
        </VirtGridRoot>
      </div>
    </div>
  );
}
